### ISSUE TITLE
can't compile with electron

### ISSUE THREAD

**Issue by ssssota** [devongovett/font-manager#42]
I tried [electron-quick-start](https://github.com/electron/electron-quick-start) with font-manager module.

1. `git clone https://github.com/electron/electron-quick-start`
2. `cd electron-quick-start`
3. `npm install`
4. `npm start` <- i can
5. `npm install font-manager`
6. `npm install --save-dev electron-rebuild`
7. add script `"electron:rebuild":"electron-rebuild -f -w font-manager"`

my environment

- Ubuntu 18.04
- node 12.13.1
- npm 6.12.1

I'm sorry. I can't use english well. And this is my first issue.

```
electron-quick-start ❯❯❯ npm run electron:rebuild

> electron-quick-start@1.0.0 electron:rebuild /home/ssssota/Documents/electron-quick-start
> electron-rebuild -w font-manager

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
make: ディレクトリ '/home/ssssota/Documents/electron-quick-start/node_modules/font-manager/build'　に入ります
  CXX(target) Release/obj.target/fontmanager/src/FontManager.o
In file included from /home/ssssota/.electron-gyp/7.1.2/include/node/v8-internal.h:14:0,
                 from /home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:27,
                 from /home/ssssota/.electron-gyp/7.1.2/include/node/node.h:63,
                 from ../src/FontManager.cc:2:
/home/ssssota/.electron-gyp/7.1.2/include/node/v8config.h:343:49: warning: ‘MicrotasksCompletedCallback’ is deprecated [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))
                                                 ^
/home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:8513:3: note: in expansion of macro ‘V8_DEPRECATE_SOON’
   V8_DEPRECATE_SOON("Use *WithData version.",
   ^~~~~~~~~~~~~~~~~
/home/ssssota/.electron-gyp/7.1.2/include/node/v8config.h:343:49: warning: ‘MicrotasksCompletedCallback’ is deprecated [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))
                                                 ^
/home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:8522:3: note: in expansion of macro ‘V8_DEPRECATE_SOON’
   V8_DEPRECATE_SOON("Use *WithData version.",
   ^~~~~~~~~~~~~~~~~
In file included from ../src/FontManager.cc:6:0:
../src/FontDescriptor.h: In member function ‘bool FontDescriptor::getBool(v8::Local<v8::Object>, const char*)’:
../src/FontDescriptor.h:176:75: error: no matching function for call to ‘v8::Value::BooleanValue(v8::Local<v8::Context>)’
       return value.ToLocalChecked()->BooleanValue(Nan::GetCurrentContext()).FromJust();
                                                                           ^
In file included from /home/ssssota/.electron-gyp/7.1.2/include/node/node.h:63:0,
                 from ../src/FontManager.cc:2:
/home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:2653:8: note: candidate: bool v8::Value::BooleanValue(v8::Isolate*) const
   bool BooleanValue(Isolate* isolate) const;
        ^~~~~~~~~~~~
/home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:2653:8: note:   no known conversion for argument 1 from ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
In file included from /home/ssssota/.electron-gyp/7.1.2/include/node/v8-internal.h:14:0,
                 from /home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:27,
                 from /home/ssssota/.electron-gyp/7.1.2/include/node/node.h:63,
                 from ../src/FontManager.cc:2:
/home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:2662:43: note: candidate: bool v8::Value::BooleanValue() const
   V8_DEPRECATED("Use maybe version", bool BooleanValue() const);
                                           ^
/home/ssssota/.electron-gyp/7.1.2/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:2662:43: note:   candidate expects 0 arguments, 1 provided
   V8_DEPRECATED("Use maybe version", bool BooleanValue() const);
                                           ^
/home/ssssota/.electron-gyp/7.1.2/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
fontmanager.target.mk:110: recipe for target 'Release/obj.target/fontmanager/src/FontManager.o' failed
make: *** [Release/obj.target/fontmanager/src/FontManager.o] Error 1
make: ディレクトリ '/home/ssssota/Documents/electron-quick-start/node_modules/font-manager/build' から出ます
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ssssota/Documents/electron-quick-start/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-70-generic
gyp ERR! command "/usr/local/bin/node" "/home/ssssota/Documents/electron-quick-start/node_modules/.bin/node-gyp" "rebuild" "--target=7.1.2" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/ssssota/Documents/electron-quick-start/node_modules/font-manager
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok 

Failed with exit code: 1

Error: make: ディレクトリ '/home/ssssota/Documents/electron-quick-start/node_modules/font-manager/build'　に入ります
  CXX(target) Release/obj.target/fontmanager/src/FontManager.o
In file included from /home/ssssota/.electron-gyp/7.1.2/include/node/v8-internal.h:14:0,
                 from /home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:27,
                 from /home/ssssota/.electron-gyp/7.1.2/include/node/node.h:63,
                 from ../src/FontManager.cc:2:
/home/ssssota/.electron-gyp/7.1.2/include/node/v8config.h:343:49: warning: ‘MicrotasksCompletedCallback’ is deprecated [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))
                                                 ^
/home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:8513:3: note: in expansion of macro ‘V8_DEPRECATE_SOON’
   V8_DEPRECATE_SOON("Use *WithData version.",
   ^~~~~~~~~~~~~~~~~
/home/ssssota/.electron-gyp/7.1.2/include/node/v8config.h:343:49: warning: ‘MicrotasksCompletedCallback’ is deprecated [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))
                                                 ^
/home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:8522:3: note: in expansion of macro ‘V8_DEPRECATE_SOON’
   V8_DEPRECATE_SOON("Use *WithData version.",
   ^~~~~~~~~~~~~~~~~
In file included from ../src/FontManager.cc:6:0:
../src/FontDescriptor.h: In member function ‘bool FontDescriptor::getBool(v8::Local<v8::Object>, const char*)’:
../src/FontDescriptor.h:176:75: error: no matching function for call to ‘v8::Value::BooleanValue(v8::Local<v8::Context>)’
       return value.ToLocalChecked()->BooleanValue(Nan::GetCurrentContext()).FromJust();
                                                                           ^
In file included from /home/ssssota/.electron-gyp/7.1.2/include/node/node.h:63:0,
                 from ../src/FontManager.cc:2:
/home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:2653:8: note: candidate: bool v8::Value::BooleanValue(v8::Isolate*) const
   bool BooleanValue(Isolate* isolate) const;
        ^~~~~~~~~~~~
/home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:2653:8: note:   no known conversion for argument 1 from ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
In file included from /home/ssssota/.electron-gyp/7.1.2/include/node/v8-internal.h:14:0,
                 from /home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:27,
                 from /home/ssssota/.electron-gyp/7.1.2/include/node/node.h:63,
                 from ../src/FontManager.cc:2:
/home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:2662:43: note: candidate: bool v8::Value::BooleanValue() const
   V8_DEPRECATED("Use maybe version", bool BooleanValue() const);
                                           ^
/home/ssssota/.electron-gyp/7.1.2/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/ssssota/.electron-gyp/7.1.2/include/node/v8.h:2662:43: note:   candidate expects 0 arguments, 1 provided
   V8_DEPRECATED("Use maybe version", bool BooleanValue() const);
                                           ^
/home/ssssota/.electron-gyp/7.1.2/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
fontmanager.target.mk:110: recipe for target 'Release/obj.target/fontmanager/src/FontManager.o' failed
make: *** [Release/obj.target/fontmanager/src/FontManager.o] Error 1
make: ディレクトリ '/home/ssssota/Documents/electron-quick-start/node_modules/font-manager/build' から出ます
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ssssota/Documents/electron-quick-start/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-70-generic
gyp ERR! command "/usr/local/bin/node" "/home/ssssota/Documents/electron-quick-start/node_modules/.bin/node-gyp" "rebuild" "--target=7.1.2" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/ssssota/Documents/electron-quick-start/node_modules/font-manager
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/ssssota/Documents/electron-quick-start/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/home/ssssota/Documents/electron-quick-start/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/home/ssssota/Documents/electron-quick-start/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/home/ssssota/Documents/electron-quick-start/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/home/ssssota/Documents/electron-quick-start/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/home/ssssota/Documents/electron-quick-start/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/home/ssssota/Documents/electron-quick-start/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/home/ssssota/Documents/electron-quick-start/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/home/ssssota/Documents/electron-quick-start/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/ssssota/Documents/electron-quick-start/node_modules/rxjs/internal/Subscriber.js:143:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! electron-quick-start@1.0.0 electron:rebuild: `electron-rebuild -w font-manager`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 electron:rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ssssota/.npm/_logs/2019-11-22T00_53_27_683Z-debug.log
```

**Comment by polyrhythmatic** [comment]
Having the exact same issue, but I seem unable to get this to build with any version of node. Has anyone had success with this?

edit: installed #43 and it works great!
