### ISSUE TITLE
Not compatible with gyp

### ISSUE THREAD

**Issue by baolintian** [devongovett/font-manager#51]
linux 19.04
v10.15.2
error info:

> ../src/FontManager.cc: In instantiation of ‘Nan::NAN_METHOD_RETURN_TYPE substituteFont(Nan::NAN_METHOD_ARGS_TYPE) [with bool async = false; Nan::NAN_METHOD_RETURN_TYPE = void; Nan::NAN_METHOD_ARGS_TYPE = const Nan::FunctionCallbackInfo<v8::Value>&]’:
../src/FontManager.cc:220:66:   required from here
../src/FontManager.cc:204:71: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
make: *** [fontmanager.target.mk:104: Release/obj.target/fontmanager/src/FontManager.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/danmaku-to-ass/node_modules/font-manager/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.3.0-40-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/danmaku-to-ass/node_modules/font-manager
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! font-manager@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the font-manager@0.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-06T15_30_54_929Z-debug.log

Can anyone help me to solve this problem? Thanks a lot~

**Comment by Jayce-liang** [comment]
解决了吗哥？ what is ths soluction
